# Generated by Django 5.0.4 on 2024-05-18 13:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('rates', '0001_initial'),
        ('settings', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('block_position_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Коэффициент позиционирования в блоке')),
                ('month_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Сезонный коэффициент')),
                ('other_person_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Коэффициент за упоминание 3-х лиц')),
                ('hour_selected_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Коэффициент за выбор часа')),
                ('order_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Сумма заказа, руб.')),
                ('order_amount_discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка за сумму заказа, %')),
                ('total_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Количество дней')),
                ('order_days_discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка за продолжительность РК, %')),
                ('order_volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(527)], verbose_name='Количество выходов')),
                ('order_volume_discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка за кол-во выходов в сетке, %')),
                ('final_order_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Итого к оплате, руб.')),
                ('block_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_block_position', to='rates.blockposition', verbose_name='Позиционирование в блоке')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_city', to='settings.city', verbose_name='Город')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='customers.customer', verbose_name='Покупатель')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_month', to='settings.month', verbose_name='Месяц')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_station', to='stations.radiostation', verbose_name='Радиостанция')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderCustomerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Число месяца')),
                ('interval_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Цена, руб.')),
                ('audio_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_selection_audio_duration', to='settings.audioduration', verbose_name='Хронометраж ролика, сек')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_selection_order', to='orders.order', verbose_name='Заказ')),
                ('time_interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_selection_time_interval', to='settings.timeinterval', verbose_name='Часовой интервал')),
                ('week_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_selection_week_day', to='settings.weekday', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Выбор клиента',
                'verbose_name_plural': 'Выбор клиента',
                'ordering': ('date',),
            },
        ),
    ]
