version: '3.3'
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    user: "70:70"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    networks:
      - db_network
    expose:
      - '${DB_PORT}'
    container_name: ekb_radio_db

  pgadmin:
    image: dpage/pgadmin4:8.5
    restart: always
    user: "5050:0"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env.dev
    networks:
      - db_network
      - pgadmin_network
    depends_on:
      - postgres
    expose:
      - 1043
    container_name: ekb_radio_pgadmin

  redis:
    image: redis:7.2.4-alpine
    restart: always
    user: "999:1000"
    volumes:
      - redis_data:/data
      - .redis:/home/redis/redis.conf
    command: redis-server /home/redis/redis.conf
    networks:
      - redis_network
    expose:
      - '${REDIS_PORT}'
    container_name: ekb_radio_redis

  backend:
    build: ../backend
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: "backend.settings"
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
      - api_docs_value:/backend/static/docs/
    env_file:
      - .env.dev
    networks:
      - db_network
      - redis_network
      - backend_network
    expose:
      - '${BACKEND_PORT}'
    depends_on:
      - postgres
      - redis
    container_name: ekb_radio_backend

  frontend:
    build:
      context: ../frontend
      dockerfile: DockerfileDev
    volumes:
      - frontend_value:/frontend/dist/
    depends_on:
      - backend
    container_name: ekb_radio_frontend

  nginx:
    image: nginx:1.25.5-alpine-slim
    restart: always
    volumes:
      - ./nginx_dev.conf:/etc/nginx/conf.d/default.conf
      - frontend_value:/usr/share/nginx/html/
      - static_value:/usr/share/nginx/html/static/
      - media_value:/usr/share/nginx/html/media/
      - api_docs_value:/usr/share/nginx/html/api/docs/
    ports:
      - "80:80"
    networks:
      - redis_network
      - backend_network
      - pgadmin_network
    depends_on:
      - backend
    container_name: ekb_radio_nginx

networks:
  backend_network:
  db_network:
  redis_network:
  pgadmin_network:

volumes:
  postgres_data:
  pgadmin_data:
  static_value:
  media_value:
  api_docs_value:
  redis_data:
  frontend_value:
