version: '3.3'
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    networks:
      - db_network
    expose:
      - 5432
    container_name: ekb_radio_db

#  pgadmin:
#    image: dpage/pgadmin4:7.6
#    restart: always
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    env_file:
#      - .env.dev
#    networks:
#      - db_network
#      - pgadmin_network
#    depends_on:
#      - postgres
#    expose:
#      - 1043
#    container_name: ekb_radio_pgadmin

  redis:
    image: redis:7.2.1-alpine
    restart: always
    volumes:
      - redis_data:/data
      - .redis:/home/redis/redis.conf
    command: redis-server /home/redis/redis.conf
    networks:
      - redis_network
    expose:
      - 6379
    container_name: ekb_radio_redis

  backend:
    build: ../backend
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: "backend.settings"
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
      - api_docs_value:/backend/static/docs/
    env_file:
      - .env.dev
    networks:
      - db_network
      - redis_network
      - backend_network
    expose:
      - 8000
    depends_on:
      - postgres
      - redis
    container_name: ekb_radio_backend

#  frontend:
#    build:
#      context: ../frontend
#      dockerfile: DockerfileLocal
#    volumes:
#      - frontend_value:/frontend/dist/
#      - storybook_value:/frontend/storybook-static/
#    depends_on:
#      - postgres
#    container_name: ekb_radio_frontend

  nginx:
    image: nginx:1.25.2-alpine-slim
    restart: always
    volumes:
      - ./nginx_dev.conf:/etc/nginx/conf.d/default.conf
#      - frontend_value:/usr/share/nginx/html/
      - static_value:/usr/share/nginx/html/static/
      - media_value:/usr/share/nginx/html/media/
      - api_docs_value:/usr/share/nginx/html/api/docs/
    ports:
      - "80:80"
    networks:
      - redis_network
      - backend_network
#      - pgadmin_network
    depends_on:
      - backend
#      - pgadmin
    container_name: ekb_radio_nginx

networks:
  backend_network:
  db_network:
  redis_network:
#  pgadmin_network:

volumes:
  postgres_data:
#  pgadmin_data:
  static_value:
  media_value:
  api_docs_value:
  redis_data:
#  frontend_value:
#  storybook_value:
