# Generated by Django 5.0.4 on 2024-05-18 13:32

import functools
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, validators=[functools.partial(utils.validators.validate_text, *(), **{'max_length': 100})], verbose_name='Название организации')),
                ('name', models.CharField(max_length=100, validators=[utils.validators.validate_user_first_or_last_name], verbose_name='Имя')),
                ('phone', models.CharField(max_length=18, validators=[utils.validators.validate_phone], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[utils.validators.validate_email], verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ('-id',),
            },
        ),
    ]
