# Generated by Django 5.0.4 on 2024-05-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-id',), 'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
    ]
