# Generated by Django 5.0.4 on 2024-05-02 17:50

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время')),
                ('excel_file', models.FileField(upload_to='import/', validators=[utils.validators.validate_excel_file], verbose_name='excel файл')),
            ],
            options={
                'verbose_name': 'Импорт данных',
                'verbose_name_plural': 'Импорт данных',
                'ordering': ('id',),
            },
        ),
    ]
