# Generated by Django 5.0.4 on 2024-05-23 15:42

import functools
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiostation',
            name='name',
            field=models.CharField(max_length=100, validators=[functools.partial(utils.validators.validate_text, *(), **{'max_length': 100})], verbose_name='Название'),
        ),
    ]
