# Generated by Django 5.0.4 on 2024-05-16 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysdiscount',
            name='total_days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Количество дней'),
        ),
        migrations.AlterField(
            model_name='volumediscount',
            name='order_volume',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(527)], verbose_name='Количество выходов'),
        ),
    ]
