# Generated by Django 5.0.4 on 2024-04-26 18:40

import django.contrib.auth.models
import django.utils.timezone
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, unique=True, validators=[utils.validators.validate_email], verbose_name='Email')),
                ('username', models.CharField(max_length=50, unique=True, validators=[utils.validators.validate_username], verbose_name='Никнэйм')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, validators=[utils.validators.validate_user_first_or_last_name], verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, validators=[utils.validators.validate_user_first_or_last_name], verbose_name='Фамилия')),
                ('password', models.CharField(max_length=150, validators=[utils.validators.validate_password], verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=False, verbose_name='Пользователь активированный')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
